name: Build All Cores (3/3 — Custom)

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  core_fake08:
    uses: ./.github/workflows/build-fake08.yml

  core_libgametank:
    uses: ./.github/workflows/build-libgametank.yml

  core_km_duckswanstation_xtreme_amped:
    uses: ./.github/workflows/build-km_duckswanstation_xtreme_amped.yml

  core_km_parallel_n64_xtreme_amped_turbo:
    uses: ./.github/workflows/build-km_parallel_n64_xtreme_amped_turbo.yml

  core_km_vjag_xtreme_amped:
    uses: ./.github/workflows/build-km_vjag_xtreme_amped.yml
